### PR TITLE
fixed method naming

### PR DESCRIPTION
**Pull request by cxoltero**

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
Can one of the admins verify this patch?

**Comment by paul-barry-kenzan** [comment]
This looks ok. ok to test ?

**Comment by obuckley-kenzan** [comment]
ok to test

**Comment by obuckley-kenzan** [comment]
ok to test

**Comment by obuckley-kenzan** [comment]
@cxoltero 
Looks like my PR #18 introduced a merge conflict

**Comment by obuckley-kenzan** [comment]
resolves issue #20

**Pull request merged**
